/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SshRouteImport } from './routes/ssh'
import { Route as SettingRouteImport } from './routes/setting'

const SshRoute = SshRouteImport.update({
  id: '/ssh',
  path: '/ssh',
  getParentRoute: () => rootRouteImport,
})
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  SettingRoute: SettingRoute,
  SshRoute: SshRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
